version: '3'

services:
  rustapp:
    container_name: rustume
    image: rustume:0.5.0
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: "postgres://postgres:postgres@my_db:5432/postgres"
    ports:
      - '8000:8000'
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}