[default.databases.my_db]
url = "postgres://postgres:Jordago99!@localhost/users"
#url = "postgres://jordangarske:BridgeAndRemy1414@rustumedb.ctty7jlgirvi.us-east-1.rds.amazonaws.com:5432/rustumeDB"
[default]
secret_key = "5lGEQSJqDo0gy34R3QC7C958vn6VUrOsPlWbUChMrDs="
# address = "0.0.0.0"
# port = 80